services:
  - name: car-price-predictor
    type: web
    env: python
    plan: free
    buildcmd: |
      pip install -r requirements.txt
    startcmd: |
      startcmd: uvicorn api:app --host 0.0.0.0 --port 10000
